apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-app-cluster
  region: us-west-2
  version: "1.21"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    labels: 
      role: frontend
    ssh:
      allow: true
      publicKeyName: my-key-pair

  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    labels: 
      role: backend
    ssh:
      allow: true
      publicKeyName: my-key-pair
